#Basic Vector and Matrix Operation with Numpy.

# Problem - 1: Array Creation:

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2

In [ ]:
empty_array = np.empty((2, 2))
print("Empty 2x2 Array:\n", empty_array)

Empty 2x2 Array:
 [[1.89243451e-316 0.00000000e+000]
 [1.91140757e-316 7.90505033e-323]]


# 2. Initialize an all-one array with size 4x2

In [ ]:
ones_array = np.ones((4, 2))
print("\nAll Ones 4x2 Array:\n", ones_array)


All Ones 4x2 Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


# 3. Return a new array of given shape and type, filled with fill value (e.g., 7)

In [ ]:
filled_array = np.full((3, 3), 7)
print("\n3x3 Array Filled with 7:\n", filled_array)



3x3 Array Filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


# 4. Return a new array of zeros with same shape and type as a given array

In [ ]:
reference_array = np.array([[1, 2, 3], [4, 5, 6]])  # Example reference array
zeros_like_array = np.zeros_like(reference_array)
print("\nZeros Array with Same Shape as Reference Array:\n", zeros_like_array)


Zeros Array with Same Shape as Reference Array:
 [[0 0 0]
 [0 0 0]]


# 5. Return a new array of ones with same shape and type as a given array

In [ ]:
ones_like_array = np.ones_like(reference_array)
print("\nOnes Array with Same Shape as Reference Array:\n", ones_like_array)


Ones Array with Same Shape as Reference Array:
 [[1 1 1]
 [1 1 1]]


# 6. Convert an existing list to a NumPy array

In [ ]:
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted NumPy Array from List:\n", numpy_array)


Converted NumPy Array from List:
 [1 2 3 4]


#Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

# 1. Create an array with values ranging from 10 to 49

In [ ]:
array_range = np.arange(10, 50)
print("Array with values from 10 to 49:\n", array_range)

Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 2. Create a 3X3 matrix with values ranging from 0 to 8

In [ ]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix with values from 0 to 8:\n", matrix_3x3)



3x3 Matrix with values from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


# 3. Create a 3X3 identity matrix

In [ ]:

identity_matrix = np.eye(3)
print("\n3x3 Identity Matrix:\n", identity_matrix)


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 4. Create a random array of size 30 and find the mean


In [ ]:
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nMean of Random Array (size 30):", mean_value)


Mean of Random Array (size 30): 0.4651091763512111


# 5. Create a 10X10 array with random values and find min & max values

In [ ]:
random_matrix = np.random.random((10, 10))
min_value = random_matrix.min()
max_value = random_matrix.max()
print("\nMinimum Value in 10x10 Random Matrix:", min_value)
print("Maximum Value in 10x10 Random Matrix:", max_value)


Minimum Value in 10x10 Random Matrix: 0.0014011211032597393
Maximum Value in 10x10 Random Matrix: 0.9882038075167588


# 6. Create a zero array of size 10 and replace 5th element with 1

In [ ]:
zero_array = np.zeros(10)
zero_array[4] = 1  # 5th element (index 4) is set to 1
print("\nZero Array with 5th Element as 1:\n", zero_array)



Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 7. Reverse an array arr = [1,2,0,0,4,0]

In [ ]:
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed Array:\n", reversed_arr)


Reversed Array:
 [0 4 0 0 2 1]



# 8. Create a 2D array with 1 on border and 0 inside

In [ ]:

border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D Array with 1 on Border and 0 Inside:\n", border_array)


2D Array with 1 on Border and 0 Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 9. Create an 8X8 matrix and fill it with a checkerboard pattern

In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard Pattern:\n", checkerboard)


8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#Problem - 3: Array Operations:

# Given arrays

In [ ]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])


# 1. Add the two arrays

In [ ]:
add_xy = x + y
print("Addition of x and y:\n", add_xy)

Addition of x and y:
 [[ 6  8]
 [10 13]]


# 2. Subtract the two arrays

In [ ]:
sub_xy = x - y
print("\nSubtraction of x and y:\n", sub_xy)


Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]


# 3. Multiply the array with any integer (e.g., 3)

In [ ]:
mult_x = x * 3
print("\nMultiplication of x with 3:\n", mult_x)


Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]


# 4. Find the square of each element of the array

In [ ]:
square_x = np.square(x)
print("\nSquare of each element in x:\n", square_x)


Square of each element in x:
 [[ 1  4]
 [ 9 25]]


# 5. Find the dot product

In [ ]:
dot_vw = np.dot(v, w)  # Dot product of v and w
dot_xv = np.dot(x, v)  # Dot product of x and v
dot_xy = np.dot(x, y)  # Dot product of x and y

print("\nDot Product of v and w:", dot_vw)
print("Dot Product of x and v:\n", dot_xv)
print("Dot Product of x and y:\n", dot_xy)



Dot Product of v and w: 219
Dot Product of x and v:
 [29 77]
Dot Product of x and y:
 [[19 22]
 [50 58]]


# 6. Concatenate x and y along rows

In [ ]:
concat_xy_row = np.concatenate((x, y), axis=0)
print("\nConcatenation of x and y along rows:\n", concat_xy_row)



Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]


# Concatenate v and w along columns

In [ ]:

concat_vw_col = np.vstack((v, w))
print("\nConcatenation of v and w along columns:\n", concat_vw_col)



Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]


# 7. Concatenate x and v

In [ ]:
try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError while concatenating x and v:", e)



Error while concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Explanation
Addition & Subtraction:

x + y → Element-wise addition.
x - y → Element-wise subtraction.
Multiplication:

x * 3 → Multiplies each element of x by 3.
Square:

np.square(x) → Computes the square of each element in x.
Dot Product:

np.dot(v, w) → Dot product of 1D vectors v and w.
np.dot(x, v) → Matrix-vector multiplication (dot product).
np.dot(x, y) → Matrix-matrix multiplication.
Concatenation:

np.concatenate((x, y), axis=0) → Stacks x and y along rows.
np.vstack((v, w)) → Stacks v and w vertically (along columns).
Concatenation Error (x and v):

x has shape (2,2), and v has shape (2,) (1D vector).
Direct concatenation fails because x is a 2D matrix, while v is 1D.
To fix this, reshape v using v.reshape(1, -1) before concatenation.

#Problem - 4: Matrix Operations:

# Given Matrices

In [ ]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A⁻¹ = I


In [ ]:
A_inv = np.linalg.inv(A)  # Compute Inverse of A
identity_matrix = np.dot(A, A_inv)  # A * A⁻¹

print("A * A⁻¹:\n", identity_matrix)

A * A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


# 2. Prove AB ≠ BA

In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("\nAB:\n", AB)
print("\nBA:\n", BA)



AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]


# Checking if AB == BA

In [ ]:
if np.array_equal(AB, BA):
    print("\nAB = BA (which is incorrect)")
else:
    print("\nAB ≠ BA (proved!)")



AB ≠ BA (proved!)


# 3. Prove (AB)^T = B^T * A^T


In [ ]:
AB_T = np.transpose(AB)
B_T = np.transpose(B)
A_T = np.transpose(A)
BT_AT = np.dot(B_T, A_T)

print("\n(AB)^T:\n", AB_T)
print("\nB^T * A^T:\n", BT_AT)



(AB)^T:
 [[23 51]
 [13 29]]

B^T * A^T:
 [[23 51]
 [13 29]]


# Checking equality

In [ ]:
if np.array_equal(AB_T, BT_AT):
    print("\n(AB)^T = B^T * A^T (proved!)")
else:
    print("\n(AB)^T ≠ B^T * A^T (incorrect)")


(AB)^T = B^T * A^T (proved!)


# --- Solve System of Linear Equations using Inverse Method ---
# Given equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

In [ ]:
# Represent in Matrix form: AX = B
A_eq = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B_eq = np.array([-1, -3, 9])

#Solve for X using inverse method
A_inv_eq = np.linalg.inv(A_eq)  # Compute inverse of A_eq
X = np.dot(A_inv_eq, B_eq)  # Solution X = A⁻¹ * B

print("\nSolution for x, y, z:\n", X)


Solution for x, y, z:
 [ 2.  1. -2.]


#10.2 Experiment: How Fast is Numpy?

In [ ]:
import time
import numpy as np

In [ ]:
# 1. Element-wise Addition
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

In [ ]:
# Using Python Lists
start = time.time()
list_sum = [list1[i] + list2[i] for i in range(size)]
end = time.time()
print(f"Python List Addition Time: {end - start:.6f} seconds")

Python List Addition Time: 0.086921 seconds


In [ ]:
# Using NumPy Arrays
arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
numpy_sum = arr1 + arr2
end = time.time()
print(f"NumPy Array Addition Time: {end - start:.6f} seconds")

NumPy Array Addition Time: 0.004848 seconds


# 2. Element-wise Multiplication

In [ ]:
# Using Python Lists
start = time.time()
list_mul = [list1[i] * list2[i] for i in range(size)]
end = time.time()
print(f"Python List Multiplication Time: {end - start:.6f} seconds")

Python List Multiplication Time: 0.100557 seconds


In [ ]:
# Using NumPy Arrays
start = time.time()
numpy_mul = arr1 * arr2
end = time.time()
print(f"NumPy Array Multiplication Time: {end - start:.6f} seconds")

NumPy Array Multiplication Time: 0.003854 seconds


# 3. Dot Product

In [ ]:
# Using Python Lists
start = time.time()
dot_product = sum(list1[i] * list2[i] for i in range(size))
end = time.time()
print(f"Python List Dot Product Time: {end - start:.6f} seconds")

Python List Dot Product Time: 0.099851 seconds


In [ ]:
# Using NumPy Arrays
start = time.time()
numpy_dot_product = np.dot(arr1, arr2)
end = time.time()
print(f"NumPy Array Dot Product Time: {end - start:.6f} seconds")

NumPy Array Dot Product Time: 0.001942 seconds


# 4. Matrix Multiplication

In [ ]:
matrix_size = 1000

# Using Python Lists
mat1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
mat2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]

start = time.time()
result = [[sum(a * b for a, b in zip(row, col)) for col in zip(*mat2)] for row in mat1]
end = time.time()
print(f"Python List Matrix Multiplication Time: {end - start:.6f} seconds")

# Using NumPy Arrays
np_mat1 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)
np_mat2 = np.arange(matrix_size**2).reshape(matrix_size, matrix_size)

start = time.time()
numpy_mat_mul = np.matmul(np_mat1, np_mat2)
end = time.time()
print(f"NumPy Array Matrix Multiplication Time: {end - start:.6f} seconds")


Python List Matrix Multiplication Time: 166.980401 seconds
NumPy Array Matrix Multiplication Time: 1.235594 seconds
